#!/usr/bin/env bash

submaps() {
    if [[ ${1:0:6} == "submap" ]]; then
        export submap=${1:8}
    fi

    #output eww widget
    if [ ! -z "${submap}" ]; then
        echo "(eventbox :onclick \"hyprctl dispatch submap reset\" \
                  (box	:class \"submaps\"	:orientation \"h\" :spacing 0 :space-evenly \"true\" \"$submap\") \
              )"
    else
        echo ""
    fi
}

submaps

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do
    submaps "$event"
done
