#!/usr/bin/env bash

#define icons for workspaces 1-9
ic=(󰜌 󰜋 1)

#initial check for occupied workspaces
for num in $(hyprctl workspaces | grep ID | awk 'NR>1{print $1}' RS='(' FS=')'); do
    export o"$num"=1
done

#initial check for focused workspace
for num in $(hyprctl monitors | grep active | awk 'NR>1{print $1}' RS='(' FS=')'); do
    export f"$num"=1
    export fnum=f"$num"
done

workspaces() {
    if [[ ${1:0:10} == "workspace>" ]]; then #set focused workspace
        unset -v "$fnum"
        num=${1:11}
        export f"$num"=1
        export fnum=f"$num"

    elif [[ ${1:0:16} == "createworkspace>" ]]; then #set Occupied workspace
        num=${1:17}
        export o"$num"=1
        # export f"$num"=1

    elif [[ ${1:0:17} == "destroyworkspace>" ]]; then #unset unoccupied workspace
        num=${1:18}
        unset -v o"$num" f"$num"
    fi

    #output eww widget
    echo "(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
          (box	:class \"works\"	:orientation \"h\" :spacing 0 :space-evenly \"true\" 	\
              (button :width 26 :height 26 :onclick \"hyprctl dispatch workspace 1\" :class \"w0$o1$f1\" \"${ic[$o1]}\") \
              (button :width 26 :height 26 :onclick \"hyprctl dispatch workspace 2\" :class \"w0$o2$f2\" \"${ic[$o2]}\") \
              (button :width 26 :height 26 :onclick \"hyprctl dispatch workspace 3\" :class \"w0$o3$f3\" \"${ic[$o3]}\") \
              (button :width 26 :height 26 :onclick \"hyprctl dispatch workspace 4\" :class \"w0$o4$f4\" \"${ic[$o4]}\") \
              (button :width 26 :height 26 :onclick \"hyprctl dispatch workspace 5\" :class \"w0$o5$f5\" \"${ic[$o5]}\") \
              (button :width 26 :height 26 :onclick \"hyprctl dispatch workspace 6\" :class \"w0$o6$f6\" \"${ic[$o6]}\") \
              (button :width 26 :height 26 :onclick \"hyprctl dispatch workspace 7\" :class \"w0$o7$f7\" \"${ic[$o7]}\") \
              (button :width 26 :height 26 :onclick \"hyprctl dispatch workspace 8\" :class \"w0$o8$f8\" \"${ic[$o8]}\") \
              (button :width 26 :height 26 :onclick \"hyprctl dispatch workspace 9\" :class \"w0$o9$f9\" \"${ic[$o9]}\") \
          )\
        )"
}

workspaces

socat -u UNIX-CONNECT:"$XDG_RUNTIME_DIR"/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do
    workspaces "$event"
done
